### ISSUE TITLE
Can't install app from Google play

### ISSUE THREAD

**Issue by artemnadein** [SimpleAppProjects/TouchLockHelper#1]
@thewizrd 
Hello! Thank you for your very good apps!
I don't know why, but touch lock helper not available on my device (I have mobvoi ticwatch pro 3 ultra), from phone and directly from watch (see pictures).
I manually install version 1.0.0 from GitHub and it works fine!
![Screenshot_20230325-003951](https://user-images.githubusercontent.com/128422907/227651378-1da0190d-7701-4e7c-a92f-5ff6a655f533.png)
![screen](https://user-images.githubusercontent.com/128422907/227651380-0aae4022-bf8a-456d-b1d0-e8fd4d47ab0c.png)

And please, share here version 1.0.1.

The same problem with simple wear.

**Comment by thewizrd** [comment]
Hello, the should be back on the Play Store.
Please let me know of any other issues.
